### ISSUE TITLE
map, filter, reduce 구현하기

### ISSUE THREAD

**Issue by kakasoo** [bkdragon0228/algorithm#2]
함수형 메서드들을 쓰면 코드가 더 효율적일까?
사실 그렇지는 않습니다.

```javascript
function map (arr, fn) {
    const newArr = [];
    for (const item of arr) {
        newArr.push(fn(item));
    }
    return newArr;
}

```

결과적으로 내부에 for문이 있는 건 마찬가지기 때문입니다.
기본 골격은 저렇게 map처럼 생겼고, map, filter, reduce를 이용해서 나머지 메서드 대부분을 만들 수 있습니다.

**Comment by kakasoo** [comment]
```javascript

Array.prototype.map = function () { }; // 생략

```

프로토타입으로 넣으면 기본 map처럼 Array 전체에 쓰이는 함수를 만들 수도 있습니다.
저렇게 만들면, 위 함수랑 달리 arr 대신에 this를 사용할 수 있어요.

**Comment by bkdragon0228** [comment]
프로토타입으로 넣으면 기본 map처럼 Array 전체에 쓰이는 함수를 만들 수도 있습니다.
저렇게 만들면, 위 함수랑 달리 arr 대신에 this를 사용할 수 있어요. ->이거 무슨말이죠?!?!

**Comment by kakasoo** [comment]
```javascript
Array.prototype.console = function () {
    console.log(this);
}

new Array(10).fill(0).map((el,i) => i + 1).console();

```

메서드들은 기본적으로 객체 내에서 함수를 찾지 못하면 자신의 프로토타입의 함수를 찾습니다.
그래서 map, filter, reduce는 사실 Array.prototype.map, Array.prototype.filter, Array.prototype.reduce 함수들이고요,
이런 프로토타입 함수 내부에서 this는 각각의 객체 자신을 가리킵니다.
그래서 제가 첫번째 함수 예시로 만든 것처럼,

```javascript
function map (arr, fn) {
    const newArr = [];
    for (const item of arr) {
        newArr.push(fn(item));
    }
    return newArr;
}

```

arr라는 파라미터를 받을 필요없이 그냥 this로 접근하면 된다는 거에요.

**Comment by kakasoo** [comment]
참고로 위에 Array.prototype.console은 제가 임의로 만든 함수고, 저걸 정의해놓으면 어떤 배열이든지 아래처럼 console.log()로 배열 내부를 보여줍니다.
