### ISSUE TITLE
제일 작은 수 제거하기 short coding

### ISSUE THREAD

**Issue by kakasoo** [bkdragon0228/algorithm#6]
https://github.com/bkdragon0228/algorithm/blob/44371ad9072e378bbc07db4758832b2d55cbf6e0/programmers/20210621/20210621-1.js#L3

```javascript
const solution = (arr) => arr.length > 1 ? arr.filter((el) => el !== Math.min(...arr)) : [-1];
```

arr의 length가 1 이하이면 볼 것도 없이 -1을 담은 배열을 반환하면 된다.

**Comment by bkdragon0228** [comment]
명쾌한 solution 이네요 늘 감사합니다.
